<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="DEHA games - index.html" />
        <meta name="keywords" content="DEHA GAMES, job, career, software, cloud, UI, UX, developer, engineer"/>
        <meta name="author" content="<?php echo $meta_author; ?>" />
        <link rel="stylesheet" href="styles/styles.css" />
        <title><?php echo $page_title; ?></title>
    </head>

<body>

<!-- Header -->

    <header>
    <a href="index.html">
        <img src="images/logo.png" alt="DEHA GAMES" />
        <h1>DEHA GAMES</h1>
    </a>  
    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs Positions</a></li>
            <li><a href="apply.php">Job Applications</a></li>
            <li><a href="about.php">Meet the Team</a></li>
            <li><a href="faq.php">FAQ's</a></li>
            <li><a href="mailto:info@dehagames.com.au">Contact</a></li>
        </ul>
    </nav>
    </header>