    <!-- Footer -->
    <footer>
      <p>
          <a href="https://webtech10026.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJpIjoiNzZkZjFmNWI5NmM1NDQ4ZGE2ZTA3YTlhZGE2MzNhNDciLCJwIjoiaiJ9" target="_blank">
                  Jira Project Manager</a>
                  | &copy; DEHA GAMES | 
          <a href="info@dehagames.com.au">Contact Us!</a>
      </p> 
    </footer>
  
  </body>
</html>