<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" >
        <meta name="viewport" content="width=device-width, initial-scale=1.0" >
        <meta name="description" content="<?php echo $meta_description; ?>" >
        <meta name="keywords" content="DEHA GAMES, job, career, software, cloud, UI, UX, developer, engineer">
        <meta name="author" content="<?php echo $meta_author; ?>" >
        <link rel="stylesheet" href="styles/styles.css" >
        <title><?php echo $page_title; ?></title>
    </head>

<body>

