<!-- Header -->

    <header>
    <a href="index.php">
        <img src="images/logo.png" alt="DEHA GAMES" >
        <h1>DEHA GAMES</h1>
    </a>  
    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs Positions</a></li>
            <li><a href="apply.php">Job Applications</a></li>
            <li><a href="manage.php">Manage</a></li>
            <li><a href="signup_manager.php">Sign up</a></li>
            <li><a href="about.php">Meet the Team</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="faq.php">FAQ's</a></li>
            <li><a href="mailto:info@dehagames.com.au">Contact</a></li>
        </ul>
    </nav>
    </header>